### ISSUE TITLE
Tag a release for Galaxy?

### ISSUE THREAD

**Issue by geerlingguy** [AlbanAndrieu/ansible-cmake#1]
I'd like to use this role for one of my projects, but I don't want to include a branch version or specific commit. Could you tag a release (e.g. `1.0.0`) and make sure it's on Galaxy, so I can install the specific version using `ansible-galaxy`?

**Comment by AlbanAndrieu** [comment]
Indeed I need to refresh ansible-galaxy to re import role...
There is a tag v1.0.0 and v1.0.1.
ansible-galaxy install alban.andrieu.cmake

**Comment by geerlingguy** [comment]
Thanks, works great!
